spring:
  application:
    name: analytics-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/analyticsdb
  cache:
    type: simple

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    com.DA2.analyticsservice: DEBUG