spring:
  application:
    name: comment-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/repparton_comments}

server:
  port: ${SERVER_PORT:8085}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.DA2.commentservice: DEBUG
