import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("language") || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "vi" : "en"));
  };

  const t = (key, params = {}) => {
    let translation = translations[language]?.[key] || key;

    // Replace placeholders like {name} with actual values
    if (params && typeof params === 'object') {
      Object.keys(params).forEach(paramKey => {
        const placeholder = `{${paramKey}}`;
        translation = translation.replace(placeholder, params[paramKey]);
      });
    }

    return translation;
  };

  const value = {
    language,
    setLanguage,
    toggleLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.discover": "Discover",
    "nav.search": "Search",
    "nav.playlist": "Playlist",
    "nav.messages": "Messages",
    "nav.notifications": "Notifications",
    "nav.profile": "Profile",
    "nav.upload": "Upload",
    "nav.settings": "Settings",
    "nav.genres": "Genres",
    "nav.analytics": "Analytics",
    "nav.history": "History",

    // Auth
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.signOut": "Sign Out",
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.username": "Username",
    "auth.fullName": "Full Name",

    // Common
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.update": "Update",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.viewAll": "View All",
    "common.showMore": "Show More",
    "common.showLess": "Show Less",
    "common.unreadNotifications": "unread",
    "common.allCaughtUp": "You're all caught up!",

    // Settings
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.displayName": "Display Name",
    "settings.bio": "Bio",
    "settings.website": "Website",
    "settings.saveChanges": "Save Changes",
    "settings.theme": "Theme",
    "settings.language": "Language",
    "settings.themeLight": "Light",
    "settings.themeDark": "Dark",
    "settings.themePurple": "Purple Dream",
    "settings.themeOcean": "Ocean Blue",
    "settings.themeForest": "Forest Green",
    "settings.themeSunset": "Sunset",
    "settings.themeRose": "Rose Pink",
    "settings.themeMidnight": "Midnight",
    "settings.themeCyber": "Cyberpunk",
    "settings.themeAuto": "Auto",
    "settings.notifications": "Notifications",
    "settings.emailNotifications": "Email Notifications",
    "settings.pushNotifications": "Push Notifications",
    "settings.commentNotifications": "Comment Notifications",
    "settings.followerNotifications": "New Follower Notifications",
    "settings.likes": "Likes",
    "settings.comments": "Comments",
    "settings.followers": "Followers",
    "settings.likesDesc": "Get notified when someone likes your tracks",
    "settings.commentsDesc": "Get notified about new comments on your posts",
    "settings.followersDesc": "Get notified when someone follows you",
    "settings.newMusic": "New Music from Artists",
    "settings.newMusicDesc": "Get notified when artists you follow release new tracks",
    "settings.emailDesc": "Receive notifications via email",
    "settings.pushDesc": "Receive push notifications on your device",
    "settings.privacy": "Privacy & Security",
    "settings.publicProfile": "Public Profile",
    "settings.publicProfileDesc": "Make your profile visible to everyone",
    "settings.showActivity": "Show Activity",
    "settings.showActivityDesc": "Let others see your listening activity",
    "settings.publicPlaylists": "Public Playlists",
    "settings.publicPlaylistsDesc": "Make your playlists visible to others",
    "settings.whoCanMessage": "Who can message you",
    "settings.everyone": "Everyone",
    "settings.friendsOnly": "Friends only",
    "settings.noOne": "No one",
    "settings.audioPlayback": "Audio & Playback",
    "settings.audioQuality": "Audio Quality",
    "settings.high": "High",
    "settings.medium": "Medium",
    "settings.low": "Low",
    "settings.autoplay": "Autoplay",
    "settings.autoplayDesc": "Automatically play the next track",
    "settings.crossfade": "Crossfade",
    "settings.crossfadeDesc": "Smooth transition between tracks",
    "settings.volume": "Volume",
    "settings.crossfadeDuration": "Crossfade Duration",
    "settings.crossfadeDurationDesc": "Duration of fade in/out when crossfade is enabled",
    "settings.interface": "Interface",
    "settings.showWaveform": "Show Waveform",
    "settings.showWaveformDesc": "Display audio waveform in player",
    "settings.showLyrics": "Show Lyrics",
    "settings.showLyricsDesc": "Display lyrics when available",
    "settings.animations": "Animations",
    "settings.animationsDesc": "Enable smooth animations and transitions",
    "settings.dataStorage": "Data & Storage",
    "settings.downloadData": "Download Your Data",
    "settings.downloadDataDesc": "Get a copy of all your SoundSpace data",
    "settings.request": "Request",
    "settings.deleteAccount": "Delete Account",
    "settings.deleteAccountDesc": "Permanently delete your account and all data",

    // Music
    "music.play": "Play",
    "music.pause": "Pause",
    "music.next": "Next",
    "music.previous": "Previous",
    "music.shuffle": "Shuffle",
    "music.repeat": "Repeat",
    "music.volume": "Volume",
    "music.addToPlaylist": "Add to Playlist",
    "music.share": "Share",
    "music.like": "Like",
    "music.unlike": "Unlike",
    "music.download": "Download",

    // Social
    "social.follow": "Follow",
    "social.unfollow": "Unfollow",
    "social.following": "Following",
    "social.followers": "Followers",
    "social.posts": "Posts",
    "social.comment": "Comment",
    "social.reply": "Reply",
    "social.delete": "Delete",
    "social.report": "Report",

    // Time
    "time.now": "Just now",
    "time.minutesAgo": "minutes ago",
    "time.hoursAgo": "hours ago",
    "time.daysAgo": "days ago",
    "time.weeksAgo": "weeks ago",
    "time.monthsAgo": "months ago",
    "time.yearsAgo": "years ago",

    // Genres
    "genres.title": "Music Genres",
    "genres.trending": "Trending Now",
    "genres.all": "All Genres",
    "genres.songs": "songs",

    // Analytics
    "analytics.title": "Analytics Dashboard",
    "analytics.totalPlays": "Total Plays",
    "analytics.totalListeners": "Total Listeners",
    "analytics.topSongs": "Top Songs",
    "analytics.recentSearches": "Recent Searches",
    "analytics.listenHistory": "Listen History",

    // History
    "history.title": "History",
    "history.listen": "Listen History",
    "history.search": "Search History",
    "history.clear": "Clear History",
    "history.noListenHistory": "No listen history yet",
    "history.noSearchHistory": "No search history yet",

    // Home & Feed
    "home.title": "Home",
    "home.whatsOnYourMind": "What's on your mind?",
    "home.share": "Share",
    "home.trendingSongs": "Trending Songs",
    "home.forYou": "For You",
    "home.stories": "Stories",
    "home.welcome": "Welcome back, {name}!",
    "home.welcomeArtist": "Ready to share your latest creation with the world?",
    "home.welcomeUser": "Discover new music and connect with artists you love.",
    "home.exploreTrending": "Explore Trending",
    "home.yourFeed": "Your Feed",
    "home.latestPosts": "Latest Posts",
    "home.trending": "Trending",
    "home.noPosts": "No posts yet",
    "home.noTrending": "No trending posts available",
    "home.followHint": "Follow some artists to see their posts in your feed",
    "home.signInHint": "Sign in to see personalized content",
    "home.quickActions": "Quick Actions",
    "home.createPlaylist": "Create Playlist",
    "home.discoverMusic": "Discover Music",
    "home.uploadTrack": "Upload Track",
    "home.trendingNow": "Trending Now",
    "home.seeAll": "See all",
    "home.aiRecommended": "AI Recommended for You",
    "home.post.photo": "Photo",
    "home.post.music": "Music",
    "home.post.feeling": "Feeling",
    "home.post.submit": "Post",

    // Navbar Extended
    "nav.groups": "Groups",
    "nav.admin": "Admin Dashboard",
    "nav.devices": "Devices",
    "nav.changePassword": "Change Password",


    // Discover
    "discover.title": "Discover",
    "discover.recent": "Recently Played",
    "discover.newest": "Newest Releases",
    "discover.mostViewed": "Most Popular",
    "discover.viewAll": "View All",

    // Upload
    "upload.title": "Upload",
    "upload.song": "Upload Song",
    "upload.post": "Create Post",
    "upload.selectFile": "Select File",
    "upload.songTitle": "Song Title",
    "upload.description": "Description",
    "upload.genre": "Genre",
    "upload.coverImage": "Cover Image",
    "upload.audioFile": "Audio File",
    "upload.uploading": "Uploading...",
    "upload.success": "Upload successful!",
    "upload.error": "Upload failed",

    // Profile
    "profile.posts": "Posts",
    "profile.followers": "Followers",
    "profile.following": "Following",
    "profile.editProfile": "Edit Profile",
    "profile.songs": "Songs",
    "profile.playlists": "Playlists",
    "profile.about": "About",
    "profile.friends": "Friends",
    "profile.friendsHint": "Friends are people who follow each other",
    "profile.noPosts": "No posts yet.",
    "profile.noFriends": "No friends yet.",
    "profile.noSongs": "No songs yet.",
    "profile.noPlaylists": "No playlists yet.",
    "profile.pinnedGroups": "Pinned Groups",
    "profile.viewAll": "View all",
    "profile.locked": "Content Locked",
    "profile.artistOnly": "Only Artist accounts can post songs",
    "profile.contactAdmin": "Contact admin to upgrade your account to Artist",


    // Playlist
    "playlist.myPlaylists": "My Playlists",
    "playlist.create": "Create Playlist",
    "playlist.addSong": "Add Song",
    "playlist.removeSong": "Remove Song",
    "playlist.name": "Playlist Name",
    "playlist.public": "Public",
    "playlist.private": "Private",

    // Messages
    "messages.title": "Messages",
    "messages.newMessage": "New Message",
    "messages.typeMessage": "Type a message...",
    "messages.send": "Send",
    "messages.noMessages": "No messages yet",

    // Listen Page
    "listen.noSong": "No song selected",
    "listen.chooseSong": "Choose a song to start listening",
    "listen.about": "About this track",
    "listen.plays": "plays",
    "listen.addToPlaylist": "Add to Playlist",
    "listen.tabInfo": "Info",
    "listen.tabLyrics": "Lyrics",
    "listen.tabAnalysis": "AI Analysis",
    "listen.tabCover": "Cover",
    "listen.metaArtist": "Artist",
    "listen.metaDuration": "Duration",
    "listen.metaPlays": "Plays",
    "listen.metaReleased": "Released",
    "listen.metaGenre": "Genre",
    "listen.noDescription": "No description yet.",
    "listen.lyricsTitle": "Lyrics",
    "listen.loadingLyrics": "Loading lyrics...",
    "listen.noLyrics": "No lyrics available for this song.",
    "listen.syncedLyricsAvailable": "Synced lyrics available",
    "listen.manageLyrics": "Manage Lyrics",
    "listen.coverTitle": "Cover",
    "listen.openCover": "Open cover",

    // Admin Dashboard
    "admin.title": "Admin Dashboard",
    "admin.updatedAt": "Updated at",
    "admin.refresh": "Refresh",
    "admin.quickActions": "Quick Actions",
    "admin.goToAdmin": "Go to admin page",
    "admin.manageUsers": "Manage Users",
    "admin.approveArtists": "Approve Artists",
    "admin.analytics": "Admin Analytics",
    "admin.reports": "Reports",
    "admin.totalUsers": "Total Users",
    "admin.totalAccounts": "Total accounts",
    "admin.verified": "Verified",
    "admin.verifiedDesc": "of total users",
    "admin.banned": "Banned",
    "admin.bannedAccounts": "Banned accounts",
    "admin.totalArtists": "Total Artists",
    "admin.roleArtist": "Role ARTIST",
    "admin.pending": "Pending",
    "admin.pendingArtists": "Pending artist profiles",
    "admin.approved": "Approved",
    "admin.approvedArtists": "Approved artist profiles",
    "admin.rejected": "Rejected",
    "admin.rejectedArtists": "Rejected artist profiles",
    "admin.waiting": "waiting",

    // Reports
    "reports.management": "Report Management",
    "reports.myReports": "My Reports",
    "reports.allStatus": "All Status",
    "reports.pending": "Pending",
    "reports.resolved": "Resolved",
    "reports.rejected": "Rejected",
    "reports.table.type": "Type",
    "reports.table.reason": "Reason",
    "reports.table.description": "Description",
    "reports.table.reporter": "Reporter",
    "reports.table.date": "Date",
    "reports.table.status": "Status",
    "reports.table.actions": "Actions",
    "reports.action.viewDetails": "View Details",
    "reports.action.resolve": "Resolve",
    "reports.action.reject": "Reject",
    "reports.action.delete": "Delete Report",
    "reports.confirmDelete": "Are you sure you want to delete this report? This action cannot be undone.",
    "reports.deleteTitle": "Delete Report",
    "reports.noReports": "No reports found",
    "reports.empty": "There are no reports yet",
    "reports.noReportsFilter": "No reports with status",
    "reports.detailsTitle": "Report Details",
    "reports.targetItem": "Target Item",
    "reports.noDescription": "No additional details provided.",
    "common.close": "Close",
    "common.back": "Back",
    "common.total": "Total",
    "common.page": "Page",
    "common.previous": "Previous",
    "common.next": "Next",
    "common.refresh": "Refresh",
    "common.clear": "Clear",

    // User Management Extended
    "users.searchResult": "Search results: ",
    "users.userList": "User list",
    "users.filter.allStatus": "All Status",
    "users.filter.verified": "Verified",
    "users.filter.unverified": "Unverified",
    "users.filter.allRoles": "All Roles",
    "users.filter.perPage": "/page",
    "users.noUsers": "No users found",
    "users.banModal.title": "Ban User: ",
    "users.banModal.reason": "Ban reason *",
    "users.banModal.placeholder": "Enter ban reason...",
    "users.banModal.submit": "Ban User",
    "users.banModal.banning": "Banning...",

    // Artist Approval Extended
    "artists.searchPlaceholder": "Search username/email/stage name...",
    "artists.tabs.pending": "Pending",
    "artists.tabs.approved": "Approved",
    "artists.tabs.rejected": "Rejected",
    "artists.noArtists": "No artists found",
    "artists.noArtistsMatch": "No matching artists found",
    "artists.card.stageName": "Stage Name",
    "artists.card.songCount": "Song Count",
    "artists.card.viewDoc": "View Document",
    "artists.card.social": "Social Media",
    "artists.card.rejectionReason": "Rejection Reason",
    "artists.card.approve": "Approve",
    "artists.card.reject": "Reject",
    "artists.card.approved": "Approved",
    "artists.card.rejected": "Rejected",
    "artists.rejectModal.title": "Reject Artist: ",
    "artists.rejectModal.reason": "Rejection Reason *",
    "artists.rejectModal.placeholder": "Enter rejection reason...",
    "artists.rejectModal.submit": "Reject",
    "artists.rejectModal.processing": "Rejecting...",
    "artists.detailModal.title": "Artist Application Profile",
    "artists.detailModal.accountInfo": "Account Info",
    "artists.detailModal.appInfo": "Application Info",
    "artists.detailModal.aiScore": "AI Confidence",
    "artists.detailModal.submittedAt": "Submitted At",
    "artists.detailModal.reviewedAt": "Reviewed At",
    "artists.detailModal.reviewedBy": "Reviewed By",
    "artists.detailModal.docsAndLinks": "Documents & Links",
    "artists.detailModal.openDoc": "Open Submitted Document",
    "artists.detailModal.noDoc": "No document",
    "artists.detailModal.noLinks": "No social links",

    // User Management
    "users.title": "User Management",
    "users.searchPlaceholder": "Search by name or email...",
    "users.table.user": "User",
    "users.table.role": "Role",
    "users.table.status": "Status",
    "users.table.actions": "Actions",
    "users.role.user": "User",
    "users.role.admin": "Admin",
    "users.role.artist": "Artist",
    "users.status.active": "Active",
    "users.status.banned": "Banned",
    "users.action.ban": "Ban User",
    "users.action.unban": "Unban User",
    "users.confirmBan": "Are you sure you want to ban this user?",
    "users.confirmUnban": "Are you sure you want to unban this user?",

    // Artist Approval
    "artists.title": "Artist Approvals",
    "artists.noPending": "No pending artist requests",
    "artists.table.name": "Name",
    "artists.table.bio": "Bio",
    "artists.table.genres": "Genres",
    "artists.table.requestDate": "Request Date",
    "artists.table.actions": "Actions",
    "artists.action.approve": "Approve",
    "artists.action.reject": "Reject",
    "artists.confirmApprove": "Approve this artist request?",
    "artists.confirmReject": "Reject this artist request?",
  },
  vi: {
    // Navigation
    "nav.home": "Trang chủ",
    "nav.discover": "Khám phá",
    "nav.search": "Tìm kiếm",
    "nav.playlist": "Playlist",
    "nav.messages": "Tin nhắn",
    "nav.notifications": "Thông báo",
    "nav.profile": "Hồ sơ",
    "nav.upload": "Tải lên",
    "nav.settings": "Cài đặt",
    "nav.genres": "Thể loại",
    "nav.analytics": "Phân tích",
    "nav.history": "Lịch sử",

    // Auth
    "auth.signIn": "Đăng nhập",
    "auth.signUp": "Đăng ký",
    "auth.signOut": "Đăng xuất",
    "auth.login": "Đăng nhập",
    "auth.register": "Đăng ký",
    "auth.email": "Email",
    "auth.password": "Mật khẩu",
    "auth.confirmPassword": "Xác nhận mật khẩu",
    "auth.username": "Tên người dùng",
    "auth.fullName": "Họ và tên",

    // Common
    "common.loading": "Đang tải...",
    "common.save": "Lưu",
    "common.cancel": "Hủy",
    "common.delete": "Xóa",
    "common.edit": "Chỉnh sửa",
    "common.create": "Tạo",
    "common.update": "Cập nhật",
    "common.search": "Tìm kiếm",
    "common.filter": "Lọc",
    "common.sort": "Sắp xếp",
    "common.viewAll": "Xem tất cả",
    "common.showMore": "Xem thêm",
    "common.showLess": "Thu gọn",
    "common.unreadNotifications": "chưa đọc",
    "common.allCaughtUp": "Bạn đã xem hết!",

    // Settings
    "settings.title": "Cài đặt",
    "settings.account": "Tài khoản",
    "settings.displayName": "Tên hiển thị",
    "settings.bio": "Giới thiệu",
    "settings.website": "Website",
    "settings.saveChanges": "Lưu thay đổi",
    "settings.theme": "Giao diện",
    "settings.language": "Ngôn ngữ",
    "settings.themeLight": "Sáng",
    "settings.themeDark": "Tối",
    "settings.themePurple": "Tím mộng mơ",
    "settings.themeOcean": "Xanh đại dương",
    "settings.themeForest": "Xanh rừng",
    "settings.themeSunset": "Hoàng hôn",
    "settings.themeRose": "Hồng phấn",
    "settings.themeMidnight": "Nửa đêm",
    "settings.themeCyber": "Cyberpunk",
    "settings.themeAuto": "Tự động",
    "settings.notifications": "Thông báo",
    "settings.emailNotifications": "Thông báo Email",
    "settings.pushNotifications": "Thông báo đẩy",
    "settings.commentNotifications": "Thông báo bình luận",
    "settings.followerNotifications": "Thông báo người theo dõi mới",
    "settings.likes": "Lượt thích",
    "settings.comments": "Bình luận",
    "settings.followers": "Người theo dõi",
    "settings.likesDesc": "Nhận thông báo khi có người thích bài hát của bạn",
    "settings.commentsDesc": "Nhận thông báo về bình luận mới trên bài đăng của bạn",
    "settings.followersDesc": "Nhận thông báo khi có người theo dõi bạn",
    "settings.newMusic": "Nhạc mới từ nghệ sĩ",
    "settings.newMusicDesc": "Nhận thông báo khi nghệ sĩ bạn theo dõi phát hành bài hát mới",
    "settings.emailDesc": "Nhận thông báo qua email",
    "settings.pushDesc": "Nhận thông báo đẩy trên thiết bị của bạn",
    "settings.privacy": "Quyền riêng tư & Bảo mật",
    "settings.publicProfile": "Hồ sơ công khai",
    "settings.publicProfileDesc": "Cho phép mọi người xem hồ sơ của bạn",
    "settings.showActivity": "Hiển thị hoạt động",
    "settings.showActivityDesc": "Cho phép người khác xem hoạt động nghe nhạc của bạn",
    "settings.publicPlaylists": "Playlist công khai",
    "settings.publicPlaylistsDesc": "Cho phép người khác xem playlist của bạn",
    "settings.whoCanMessage": "Ai có thể nhắn tin cho bạn",
    "settings.everyone": "Mọi người",
    "settings.friendsOnly": "Chỉ bạn bè",
    "settings.noOne": "Không ai",
    "settings.audioPlayback": "Âm thanh & Phát nhạc",
    "settings.audioQuality": "Chất lượng âm thanh",
    "settings.high": "Cao",
    "settings.medium": "Trung bình",
    "settings.low": "Thấp",
    "settings.autoplay": "Tự động phát",
    "settings.autoplayDesc": "Tự động phát bài tiếp theo",
    "settings.crossfade": "Chuyển tiếp mượt",
    "settings.crossfadeDesc": "Chuyển tiếp mượt mà giữa các bài hát",
    "settings.volume": "Âm lượng",
    "settings.crossfadeDuration": "Thời gian chuyển tiếp",
    "settings.crossfadeDurationDesc": "Thời gian fade in/out khi bật chuyển tiếp mượt",
    "settings.interface": "Giao diện",
    "settings.showWaveform": "Hiển thị dạng sóng",
    "settings.showWaveformDesc": "Hiển thị dạng sóng âm thanh trong trình phát",
    "settings.showLyrics": "Hiển thị lời bài hát",
    "settings.showLyricsDesc": "Hiển thị lời bài hát khi có sẵn",
    "settings.animations": "Hiệu ứng động",
    "settings.animationsDesc": "Bật hiệu ứng động và chuyển tiếp mượt mà",
    "settings.dataStorage": "Dữ liệu & Lưu trữ",
    "settings.downloadData": "Tải xuống dữ liệu của bạn",
    "settings.downloadDataDesc": "Nhận bản sao tất cả dữ liệu SoundSpace của bạn",
    "settings.request": "Yêu cầu",
    "settings.deleteAccount": "Xóa tài khoản",
    "settings.deleteAccountDesc": "Xóa vĩnh viễn tài khoản và tất cả dữ liệu của bạn",

    // Music
    "music.play": "Phát",
    "music.pause": "Tạm dừng",
    "music.next": "Tiếp theo",
    "music.previous": "Trước đó",
    "music.shuffle": "Ngẫu nhiên",
    "music.repeat": "Lặp lại",
    "music.volume": "Âm lượng",
    "music.addToPlaylist": "Thêm vào Playlist",
    "music.share": "Chia sẻ",
    "music.like": "Thích",
    "music.unlike": "Bỏ thích",
    "music.download": "Tải xuống",

    // Social
    "social.follow": "Theo dõi",
    "social.unfollow": "Bỏ theo dõi",
    "social.following": "Đang theo dõi",
    "social.followers": "Người theo dõi",
    "social.posts": "Bài viết",
    "social.comment": "Bình luận",
    "social.reply": "Trả lời",
    "social.delete": "Xóa",
    "social.report": "Báo cáo",

    // Time
    "time.now": "Vừa xong",
    "time.minutesAgo": "phút trước",
    "time.hoursAgo": "giờ trước",
    "time.daysAgo": "ngày trước",
    "time.weeksAgo": "tuần trước",
    "time.monthsAgo": "tháng trước",
    "time.yearsAgo": "năm trước",

    // Genres
    "genres.title": "Thể loại nhạc",
    "genres.trending": "Thịnh hành",
    "genres.all": "Tất cả thể loại",
    "genres.songs": "bài hát",

    // Analytics
    "analytics.title": "Bảng phân tích",
    "analytics.totalPlays": "Tổng lượt phát",
    "analytics.totalListeners": "Tổng người nghe",
    "analytics.topSongs": "Bài hát hàng đầu",
    "analytics.recentSearches": "Tìm kiếm gần đây",
    "analytics.listenHistory": "Lịch sử nghe",

    // History
    "history.title": "Lịch sử",
    "history.listen": "Lịch sử nghe",
    "history.search": "Lịch sử tìm kiếm",
    "history.clear": "Xóa lịch sử",
    "history.noListenHistory": "Chưa có lịch sử nghe",
    "history.noSearchHistory": "Chưa có lịch sử tìm kiếm",

    // Home & Feed
    "home.title": "Trang chủ",
    "home.whatsOnYourMind": "Bạn đang nghĩ gì?",
    "home.share": "Chia sẻ",
    "home.trendingSongs": "Bài hát thịnh hành",
    "home.forYou": "Dành cho bạn",
    "home.stories": "Tin",
    "home.welcome": "Chào mừng trở lại, {name}!",
    "home.welcomeArtist": "Sẵn sàng chia sẻ sáng tạo mới nhất của bạn với thế giới?",
    "home.welcomeUser": "Khám phá âm nhạc mới và kết nối với nghệ sĩ bạn yêu thích.",
    "home.exploreTrending": "Xem Thịnh Hành",
    "home.yourFeed": "Bảng tin",
    "home.latestPosts": "Bài viết mới nhất",
    "home.trending": "Thịnh hành",
    "home.noPosts": "Chưa có bài viết",
    "home.noTrending": "Không có bài viết thịnh hành",
    "home.followHint": "Theo dõi nghệ sĩ để xem bài viết của họ",
    "home.signInHint": "Đăng nhập để xem nội dung dành riêng cho bạn",
    "home.quickActions": "Thao tác nhanh",
    "home.createPlaylist": "Tạo Playlist",
    "home.discoverMusic": "Khám phá nhạc",
    "home.uploadTrack": "Tải lên bài hát",
    "home.trendingNow": "Đang thịnh hành",
    "home.seeAll": "Xem tất cả",
    "home.aiRecommended": "Gợi ý từ AI",
    "home.post.photo": "Ảnh",
    "home.post.music": "Nhạc",
    "home.post.feeling": "Cảm xúc",
    "home.post.submit": "Đăng",

    // Navbar Extended
    "nav.groups": "Nhóm",
    "nav.admin": "Bảng Admin",
    "nav.devices": "Thiết bị",
    "nav.changePassword": "Đổi mật khẩu",


    // Discover
    "discover.title": "Khám phá",
    "discover.recent": "Nghe gần đây",
    "discover.newest": "Mới phát hành",
    "discover.mostViewed": "Phổ biến nhất",
    "discover.viewAll": "Xem tất cả",

    // Upload
    "upload.title": "Tải lên",
    "upload.song": "Tải lên bài hát",
    "upload.post": "Tạo bài viết",
    "upload.selectFile": "Chọn tệp",
    "upload.songTitle": "Tên bài hát",
    "upload.description": "Mô tả",
    "upload.genre": "Thể loại",
    "upload.coverImage": "Ảnh bìa",
    "upload.audioFile": "Tệp âm thanh",
    "upload.uploading": "Đang tải lên...",
    "upload.success": "Tải lên thành công!",
    "upload.error": "Tải lên thất bại",

    // Profile
    "profile.posts": "Bài viết",
    "profile.followers": "Người theo dõi",
    "profile.following": "Đang theo dõi",
    "profile.editProfile": "Chỉnh sửa hồ sơ",
    "profile.songs": "Bài hát",
    "profile.playlists": "Playlist",
    "profile.about": "Giới thiệu",
    "profile.friends": "Bạn bè",
    "profile.friendsHint": "Bạn bè là những người theo dõi lẫn nhau",
    "profile.noPosts": "Chưa có bài viết nào.",
    "profile.noFriends": "Chưa có bạn bè nào.",
    "profile.noSongs": "Chưa có bài hát nào.",
    "profile.noPlaylists": "Chưa có playlist nào.",
    "profile.pinnedGroups": "Nhóm đã ghim",
    "profile.viewAll": "Xem tất cả",
    "profile.locked": "Nội dung bị khóa",
    "profile.artistOnly": "Chỉ tài khoản Nghệ sĩ mới có thể đăng bài hát",
    "profile.contactAdmin": "Liên hệ admin để nâng cấp tài khoản lên Nghệ sĩ",


    // Playlist
    "playlist.myPlaylists": "Playlist của tôi",
    "playlist.create": "Tạo Playlist",
    "playlist.addSong": "Thêm bài hát",
    "playlist.removeSong": "Xóa bài hát",
    "playlist.name": "Tên Playlist",
    "playlist.public": "Công khai",
    "playlist.private": "Riêng tư",

    // Messages
    "messages.title": "Tin nhắn",
    "messages.newMessage": "Tin nhắn mới",
    "messages.typeMessage": "Nhập tin nhắn...",
    "messages.send": "Gửi",
    "messages.noMessages": "Chưa có tin nhắn",

    // Listen Page
    "listen.noSong": "Chưa chọn bài hát nào",
    "listen.chooseSong": "Chọn một bài hát để bắt đầu nghe",
    "listen.about": "Về bài hát này",
    "listen.plays": "lượt nghe",
    "listen.addToPlaylist": "Thêm vào Playlist",
    "listen.tabInfo": "Thông tin",
    "listen.tabLyrics": "Lyrics",
    "listen.tabAnalysis": "AI Analysis",
    "listen.tabCover": "Ảnh bìa",
    "listen.metaArtist": "Nghệ sĩ",
    "listen.metaDuration": "Thời lượng",
    "listen.metaPlays": "Lượt nghe",
    "listen.metaReleased": "Ngày đăng",
    "listen.metaGenre": "Thể loại",
    "listen.noDescription": "Chưa có mô tả.",
    "listen.lyricsTitle": "Lyrics",
    "listen.loadingLyrics": "Đang tải lời bài hát...",
    "listen.noLyrics": "Chưa có lời cho bài hát này.",
    "listen.syncedLyricsAvailable": "Có lời đồng bộ theo thời gian",
    "listen.manageLyrics": "Quản lý Lyrics",
    "listen.coverTitle": "Ảnh bìa",
    "listen.openCover": "Mở ảnh bìa",

    // Admin Dashboard
    "admin.title": "Bảng Điều Khiển Admin",
    "admin.updatedAt": "Cập nhật lúc",
    "admin.refresh": "Làm mới",
    "admin.quickActions": "Thao Tác Nhanh",
    "admin.goToAdmin": "Đi tới trang quản trị",
    "admin.manageUsers": "Quản lý Users",
    "admin.approveArtists": "Duyệt Nghệ sĩ",
    "admin.analytics": "Admin Analytics",
    "admin.reports": "Báo cáo",
    "admin.totalUsers": "Tổng Users",
    "admin.totalAccounts": "Tổng số tài khoản",
    "admin.verified": "Đã Xác Thực",
    "admin.verifiedDesc": "trên tổng users",
    "admin.banned": "Bị Cấm",
    "admin.bannedAccounts": "Tài khoản bị khóa",
    "admin.totalArtists": "Tổng Nghệ sĩ",
    "admin.roleArtist": "Role ARTIST",
    "admin.pending": "Chờ Duyệt",
    "admin.pendingArtists": "Hồ sơ nghệ sĩ đang chờ",
    "admin.approved": "Đã Duyệt",
    "admin.approvedArtists": "Hồ sơ nghệ sĩ đã duyệt",
    "admin.rejected": "Từ Chối",
    "admin.rejectedArtists": "Hồ sơ nghệ sĩ bị từ chối",
    "admin.waiting": "đang chờ",

    // Reports
    "reports.management": "Quản Lý Báo Cáo",
    "reports.myReports": "Báo Cáo Của Tôi",
    "reports.allStatus": "Tất Cả Trạng Thái",
    "reports.pending": "Chờ Xử Lý",
    "reports.resolved": "Đã Giải Quyết",
    "reports.rejected": "Đã Từ Chối",
    "reports.table.type": "Loại",
    "reports.table.reason": "Lý Do",
    "reports.table.description": "Mô Tả",
    "reports.table.reporter": "Người Báo Cáo",
    "reports.table.date": "Ngày",
    "reports.table.status": "Trạng Thái",
    "reports.table.actions": "Hành Động",
    "reports.action.viewDetails": "Xem Chi Tiết",
    "reports.action.resolve": "Giải Quyết",
    "reports.action.reject": "Từ Chối",
    "reports.action.delete": "Xóa Báo Cáo",
    "reports.confirmDelete": "Bạn có chắc chắn muốn xóa báo cáo này không? Hành động này không thể hoàn tác.",
    "reports.deleteTitle": "Xóa Báo Cáo",
    "reports.noReports": "Không tìm thấy báo cáo",
    "reports.empty": "Chưa có báo cáo nào",
    "reports.noReportsFilter": "Không có báo cáo với trạng thái",
    "reports.detailsTitle": "Chi Tiết Báo Cáo",
    "reports.targetItem": "Mục Tiêu",
    "reports.noDescription": "Không có mô tả thêm.",
    "common.close": "Đóng",
    "common.back": "Quay lại",
    "common.total": "Tổng",
    "common.page": "Trang",
    "common.previous": "Trước",
    "common.next": "Sau",
    "common.refresh": "Làm mới",
    "common.clear": "Xóa",

    // User Management Extended
    "users.searchResult": "Kết quả tìm kiếm: ",
    "users.userList": "Danh sách users",
    "users.filter.allStatus": "Tất cả trạng thái",
    "users.filter.verified": "Đã xác thực",
    "users.filter.unverified": "Chưa xác thực",
    "users.filter.allRoles": "Tất cả vai trò",
    "users.filter.perPage": "/trang",
    "users.noUsers": "Không tìm thấy user nào",
    "users.banModal.title": "Cấm User: ",
    "users.banModal.reason": "Lý do cấm *",
    "users.banModal.placeholder": "Nhập lý do cấm user này...",
    "users.banModal.submit": "Cấm User",
    "users.banModal.banning": "Đang cấm...",

    // Artist Approval Extended
    "artists.searchPlaceholder": "Tìm username/email/nghệ danh...",
    "artists.tabs.pending": "Chờ Duyệt",
    "artists.tabs.approved": "Đã Duyệt",
    "artists.tabs.rejected": "Từ Chối",
    "artists.noArtists": "Không có nghệ sĩ nào",
    "artists.noArtistsMatch": "Không tìm thấy nghệ sĩ phù hợp",
    "artists.card.stageName": "Nghệ danh",
    "artists.card.songCount": "Số bài hát xác thực",
    "artists.card.viewDoc": "Xem tài liệu",
    "artists.card.social": "Mạng xã hội",
    "artists.card.rejectionReason": "Lý do từ chối",
    "artists.card.approve": "Duyệt",
    "artists.card.reject": "Từ chối",
    "artists.card.approved": "Đã duyệt",
    "artists.card.rejected": "Đã từ chối",
    "artists.rejectModal.title": "Từ Chối Nghệ Sĩ: ",
    "artists.rejectModal.reason": "Lý do từ chối *",
    "artists.rejectModal.placeholder": "Nhập lý do từ chối đơn đăng ký nghệ sĩ...",
    "artists.rejectModal.submit": "Từ Chối",
    "artists.rejectModal.processing": "Đang từ chối...",
    "artists.detailModal.title": "Hồ sơ đăng ký nghệ sĩ",
    "artists.detailModal.accountInfo": "Thông tin tài khoản",
    "artists.detailModal.appInfo": "Thông tin đăng ký",
    "artists.detailModal.aiScore": "AI confidence",
    "artists.detailModal.submittedAt": "Gửi lúc",
    "artists.detailModal.reviewedAt": "Duyệt lúc",
    "artists.detailModal.reviewedBy": "Duyệt bởi",
    "artists.detailModal.docsAndLinks": "Tài liệu & liên kết",
    "artists.detailModal.openDoc": "Mở tài liệu đã gửi",
    "artists.detailModal.noDoc": "Không có tài liệu",
    "artists.detailModal.noLinks": "Không có link mạng xã hội",

    // User Management
    "users.title": "Quản Lý Người Dùng",
    "users.searchPlaceholder": "Tìm kiếm theo tên hoặc email...",
    "users.table.user": "Người Dùng",
    "users.table.role": "Vai Trò",
    "users.table.status": "Trạng Thái",
    "users.table.actions": "Hành Động",
    "users.role.user": "Người Dùng",
    "users.role.admin": "Quản Trị Viên",
    "users.role.artist": "Nghệ Sĩ",
    "users.status.active": "Hoạt Động",
    "users.status.banned": "Bị Cấm",
    "users.action.ban": "Cấm Người Dùng",
    "users.action.unban": "Mở Khóa",
    "users.confirmBan": "Bạn có chắc chắn muốn cấm người dùng này?",
    "users.confirmUnban": "Bạn có chắc chắn muốn mở khóa cho người dùng này?",

    // Artist Approval
    "artists.title": "Duyệt Nghệ Sĩ",
    "artists.noPending": "Không có yêu cầu nào đang chờ",
    "artists.table.name": "Tên",
    "artists.table.bio": "Tiểu Sử",
    "artists.table.genres": "Thể Loại",
    "artists.table.requestDate": "Ngày Yêu Cầu",
    "artists.table.actions": "Hành Động",
    "artists.action.approve": "Phê Duyệt",
    "artists.action.reject": "Từ Chối",
    "artists.confirmApprove": "Phê duyệt yêu cầu này?",
    "artists.confirmReject": "Từ chối yêu cầu này?",
  },
};
